name: "错误报告"
description: 创建错误报告以帮助我们改进脚本
title: "[发现错误] "
labels: []
assignees: F9y4ng

body:
- type: markdown
  attributes:
    value: "## 感谢您花费几分钟宝贵的时间来反馈问题和建议。"
- type: markdown
  attributes:
    value: |
      请您在反馈问题前，确认完成以下准备工作，这能极大帮助我们快速定位问题。

- type: markdown
  attributes:
    value: "## 准备工作"
- type: checkboxes
  id: preparation
  attributes:
    label: "请务必在反馈问题前确认您已经完成以下操作，以便您的问题得到解答。"
    options:
      - label: 我确认正在使用的是当前脚本的最新版本。
        required: true
      - label: 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
        required: true
      - label: 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。
- type: dropdown
  id: select-script
  attributes:
    label: 请选择您需要反馈问题的所属脚本。
    options:
      - 字体渲染（自用脚本）
      - 优雅的搜索引擎助手
      - 自动关闭知乎登录提示
  validations:
    required: true

- type: markdown
  attributes:
    value: "## 反馈问题"
- type: textarea
  id: problem-description
  attributes:
    label: "问题描述"
    description: "清楚且简洁地描述您遇到的问题。"
    placeholder: "例：在exmaple.com站点出现脚本无法正常运行，并且控制台有报错信息。"
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: "重现步骤"
    description: "请按顺序列出可稳定重现问题的操作步骤"
    placeholder: |
      1. _去XX网址 "..."_
      2. _单击YY链接/按钮 "..."_
      3. _遇到错误或问题 "..."_
  validations:
    required: true
- type: textarea
  id: expected-result
  attributes:
    label: "预期结果"
    description: "清晰明了地描述您所期待想要什么样的结果"

- type: markdown
  attributes:
    value: "## 客户端信息"
- type: input
  id: system-info
  attributes:
    label: 操作系统及版本号
    description: 输入您所使用的操作系统和版本信息
    placeholder: 例如 Windows 11, Window 10, MacOS 26.0.1, Ubuntu 20.04
  validations:
    required: true
- type: input
  id: browser-info
  attributes:
    label: 浏览器及版本号
    description: 输入您所使用的浏览器和版本信息
    placeholder: 例如 Chrome 141.0.7390.123, Brave 1.83.120, Firefox 144.0
  validations:
    required: true
- type: input
  id: scriptmanager-info
  attributes:
    label: 脚本管理器及版本号
    description: 输入您所使用的脚本管理器和版本信息
    placeholder: 例如 Tampermonkey 5.4.0, Violentmonkey 2.31.0, Userscripts 4.8.2
  validations:
    required: true
- type: textarea
  id: troubleshooting-extensions
  attributes:
    label: "脚本运行环境排查：其他扩展"
    description: "清晰明了地描述是否同时运行了其他浏览器扩展？"
    placeholder: 例如 Dark Reader、uBlock Origin…… 等等
- type: textarea
  id: troubleshooting-scripts
  attributes:
    label: "脚本运行环境排查：其他脚本"
    description: "清晰明了地描述是否同时运行了其他第三方用户脚本？"
    placeholder: 例如 AC-baidu、Github Acceleration…… 等等

- type: markdown
  attributes:
    value: "## 其他补充信息"
- type: textarea
  id: additional-info
  attributes:
    label: "补充信息 (选填)"
    description: "错误日志/截图/脚本代码片段/相关配置..."
    placeholder: |
      脚本错误日志在脚本运行页面的开发者工具（快捷键F12）-控制台中查看
      日志空白出右键另存为日志文件，并将其上传到这里。
