name: "错误报告"
description: 创建错误报告以帮助我们改进脚本
title: "[发现错误] "
labels: []
assignees: F9y4ng

body:
- type: markdown
  attributes:
    value: "## 感谢您花费几分钟宝贵的时间来反馈问题和建议。"
- type: markdown
  attributes:
    value: |
      请您在反馈问题前，确认完成以下准备工作，这能极大帮助我们快速定位问题。
- type: checkboxes
  id: preparation
  attributes:
    label: "1. 准备工作（确认预先完成的操作）"
    options:
      - label: 我确认正在使用的是当前脚本的最新版本。
      - label: 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
      - label: 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。
- type: textarea
  id: problem-description
  attributes:
    label: "2. 问题描述"
    description: "清楚且简洁地描述您遇到的问题。"
    placeholder: "例：在exmaple.com站点出现脚本无法正常运行，并且控制台有报错信息。"
  validations:
    required: true
- type: textarea
  id: reproduction-steps
  attributes:
    label: "3. 重现步骤"
    description: "请按顺序列出可稳定重现问题的操作步骤"
    placeholder: |
      1. _去XX网址 "..."_
      2. _单击YY链接/按钮 "..."_
      3. _遇到错误或问题 "..."_
      4. -提供错误信息或问题页面的截图 "..."-
  validations:
    required: true
