name: "错误报告"
description: 创建错误报告以帮助我们改进脚本
title: "[发现错误] "
labels: []
assignees: F9y4ng

body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      **请您在反馈问题前，确认完成以下准备工作，这能极大帮助我们快速定位问题。**
- type: checkboxes
  attributes:
    label: "### 1. 准备工作（确认预先完成的操作）"
    options:
      - label: 我确认正在使用的是当前脚本的最新版本。
      - label: 我已在Issues或Discussions中搜索过此问题，但没有找到相关答案。
      - label: 我已在关闭浏览器其他扩展、仅开启此脚本的情况下测试，但依然出错。
